version: "3.9"
services:
  cetsax:
    image: ghcr.io/bibymaths/cetsax:latest
    volumes:
      - ./data:/app/data:ro
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PYTHONUNBUFFERED=1
